version: "2"
services:
  netbootxyz:
    image: razorilich/netbootxyz:latest
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./netbootxyz-config:/config
      - /media/d1/Dist/OS/netbootxyz:/assets # put here the path for the local downloaded distributives
      - /media/d1/Dist/OS/WinPE:/iso # WinPE iso
    ports:
      - 3000:3000
      - 69:69/udp 
      - 8080:80
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - USERID=1000
      - GROUPID=1000
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /media/d1/Dist/OS/netbootxyz/win:/media/d1/Dist/OS/netbootxyz/win:ro
      - /media/d1/Dist/OS/:/media/d1/Dist/OS/:z
    command: '-w "localdomain" -s "winboot;/media/d1/Dist/OS/netbootxyz/win" -s "netboot;/media/d1/Dist/OS/;yes;no;no;$USER" -u "$USER;$PASS" -p'
# or comment 69:69/udp upper and uncomment this to use dhcpproxy:
#  dhcpproxy_netboot:
#    container_name: dhcpproxy_netboot
#    image: anotherlongname/dhcpproxy-netboot
#    network_mode: host
#    environment:
#      - SUBNET=192.168.1.0

networks:
  default:
