version: "3.4"
services:
  netbootxyz:
    image: razorilich/netbootxyz
    container_name: netbootxyz
    environment:
            - PUID=1000
            - PGID=1000
            - USER=${USER}
            - WIN_10_DIR={WIN_10_DIR} 
    env_file:
      - .env 
    volumes:
      - ./configs:/config
      - /media/d1/Dist/OS/netbootxyz:/assets # put here the path for the local downloaded distributives
    ports:
      - 3000:3000
      - 69:69/udp 
      - 8080:80
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
            - USERID=1000
            - GROUPID=1000
            - USER=${U01_CLEAR};${P01_CLEAR}
            - WIN_10_DIR=${WIN_10_DIR}
            - WIN_PE_DIR=${WIN_PE_DIR} 
            - ROOT=${ROOT} 
    env_file:
      - .env
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${WIN_10_DIR}/win:/win:ro
      - ${WIN_10_DIR}/winsrv2019:/winsrv2019
      - ${WIN_10_DIR}/winsrv2016:/winsrv2016
      - ${WIN_10_DIR}/winsrv2012:/winsrv2012 
      - ${ROOT}/:/media/:z
      - ${ROOT}/WinPE/ 
    command: '-u "${U01_CLEAR};${P01_CLEAR}"
    -s "winboot;/win"
    -s "netboot;/media/"
    -s "winsrv2016;/winsrv2016"  
    -s "winsrv2012;/winsrv2012"
    -s "winsrv2019;/winsrv2019" -p '
#;yes;no;no;${U01_CLEAR}"  
    #    ;yes;no;no;${U01_CLEAR}"  -p '
# or comment 69:69/udp upper and uncomment this to use dhcpproxy:
#  dhcpproxy_netboot:
#    container_name: dhcpproxy_netboot
#    image: anotherlongname/dhcpproxy-netboot
#    network_mode: host
#    environment:
#      - SUBNET=192.168.1.0

networks:
  default:
