version: "2"
services:
  netbootxyz:
    image: razorilich/netbootxyz:latest
    container_name: netbootxyz
    environment:
            #    - PUID=1000
            # - PGID=1000
      - USER=${USER} 
    env_file:
      - .env 
    volumes:
      - $CONFIG_PATH:/config
      - $WIN_10_DIR:/assets # put here the path for the local downloaded distributives
      - $WIN_PE_DIR:/iso # WinPE iso
    ports:
      - 3000:3000
      - 69:69/udp 
      - 8080:80
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: samba
    environment:
            # - USERID=1000
            #-  GROUPID=1000
      - USER=${USER} 
    env_file:
      - .env
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ${WIN_10_DIR}/win:${WIN_10_DIR}/win:ro
      - ${OS_DIR}:${OS_DIR}:z
      - ${OS_DIR}/netboot:${OS_DIR}/config:z 
    command: '-w "$DOMAIN" -s "winboot;$WIN_10_DIR/win"   
                           -s "netboot;$WIN_10_DIR;yes;no;no;${USER} -u ${USER}" -p'                                                                   
                           # -s "config;/home/iliya/netboot;yes;no;no;${USER} -u ${USER}" -p' 



# or comment 69:69/udp upper and uncomment this to use dhcpproxy:
#  dhcpproxy_netboot:
#    container_name: dhcpproxy_netboot
#    image: anotherlongname/dhcpproxy-netboot
#    network_mode: host
#    environment:
#      - SUBNET=192.168.1.0

networks:
  default:
